--- a/Makefile	2021-08-02 08:44:57.151695339 -0700
+++ b/Makefile	2021-08-02 09:15:02.030447038 -0700
@@ -2,7 +2,7 @@
 VERSION = 5
 PATCHLEVEL = 13
 SUBLEVEL = 7
-EXTRAVERSION = -gentoo
+EXTRAVERSION = -gentoo-surface
 NAME = Opossums on Parade
 
 # *DOCUMENTATION*

